/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/Home'
import { Route as AuthNewPasswordRouteImport } from './routes/(Auth)/NewPassword'
import { Route as AuthLoginRouteImport } from './routes/(Auth)/Login'
import { Route as AuthForgotPasswordRouteImport } from './routes/(Auth)/ForgotPassword'

const HomeRoute = HomeRouteImport.update({
  id: '/Home',
  path: '/Home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNewPasswordRoute = AuthNewPasswordRouteImport.update({
  id: '/(Auth)/NewPassword',
  path: '/NewPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/(Auth)/Login',
  path: '/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/(Auth)/ForgotPassword',
  path: '/ForgotPassword',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/Home': typeof HomeRoute
  '/ForgotPassword': typeof AuthForgotPasswordRoute
  '/Login': typeof AuthLoginRoute
  '/NewPassword': typeof AuthNewPasswordRoute
}
export interface FileRoutesByTo {
  '/Home': typeof HomeRoute
  '/ForgotPassword': typeof AuthForgotPasswordRoute
  '/Login': typeof AuthLoginRoute
  '/NewPassword': typeof AuthNewPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/Home': typeof HomeRoute
  '/(Auth)/ForgotPassword': typeof AuthForgotPasswordRoute
  '/(Auth)/Login': typeof AuthLoginRoute
  '/(Auth)/NewPassword': typeof AuthNewPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/Home' | '/ForgotPassword' | '/Login' | '/NewPassword'
  fileRoutesByTo: FileRoutesByTo
  to: '/Home' | '/ForgotPassword' | '/Login' | '/NewPassword'
  id:
    | '__root__'
    | '/Home'
    | '/(Auth)/ForgotPassword'
    | '/(Auth)/Login'
    | '/(Auth)/NewPassword'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthNewPasswordRoute: typeof AuthNewPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Home': {
      id: '/Home'
      path: '/Home'
      fullPath: '/Home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Auth)/NewPassword': {
      id: '/(Auth)/NewPassword'
      path: '/NewPassword'
      fullPath: '/NewPassword'
      preLoaderRoute: typeof AuthNewPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Auth)/Login': {
      id: '/(Auth)/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(Auth)/ForgotPassword': {
      id: '/(Auth)/ForgotPassword'
      path: '/ForgotPassword'
      fullPath: '/ForgotPassword'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthNewPasswordRoute: AuthNewPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
